/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::myMath::*;


#[no_mangle]
pub unsafe extern "C" fn cffi_myMath_mul(
    a: c_int,
    b: c_int
) -> c_int
{
    myMath_mul(
        a,
        b
    )
}

#[no_mangle]
pub unsafe extern "C" fn cffi_myMath_add(
    a: c_int,
    b: c_int
) -> c_int
{
    myMath_add(
        a,
        b
    )
}

    