/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::myStack::*;


#[no_mangle]
pub unsafe extern "C" fn cffi_myStack_create(
    maxLength: c_int
) -> *mut MyStack
{
    myStack_create(
        maxLength
    )
}

#[no_mangle]
pub unsafe extern "C" fn cffi_myStack_pop(
    myStack: *mut MyStack
) -> c_int
{
    myStack_pop(
        myStack
    )
}

#[no_mangle]
pub unsafe extern "C" fn cffi_myStack_push(
    myStack: *mut MyStack,
    val: c_int
)
{
    myStack_push(
        myStack,
        val
    )
}

#[no_mangle]
pub unsafe extern "C" fn cffi_myStack_delete(
    myStack: *mut MyStack
)
{
    myStack_delete(
        myStack
    )
}

    