/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MyStack {
    pub index: ::std::os::raw::c_int,
    pub data: *mut ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MyStack"][::std::mem::size_of::<MyStack>() - 16usize];
    ["Alignment of MyStack"][::std::mem::align_of::<MyStack>() - 8usize];
    ["Offset of field: MyStack::index"][::std::mem::offset_of!(MyStack, index) - 0usize];
    ["Offset of field: MyStack::data"][::std::mem::offset_of!(MyStack, data) - 8usize];
};
extern "C" {
    pub fn myStack_create(maxLength: ::std::os::raw::c_int) -> *mut MyStack;
}
extern "C" {
    pub fn myStack_pop(myStack: *mut MyStack) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn myStack_push(myStack: *mut MyStack, val: ::std::os::raw::c_int);
}
extern "C" {
    pub fn myStack_delete(myStack: *mut MyStack);
}
