// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsbindgenHandsOn.Native
{
    internal static unsafe partial class CNativeMethodsMyMath
    {
        const string __DllName = "csbindgenhandson";



        [DllImport(__DllName, EntryPoint = "cffi_myMath_mul", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myMath_mul(int a, int b);

        [DllImport(__DllName, EntryPoint = "cffi_myMath_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myMath_add(int a, int b);


    }



}
