// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsbindgenHandsOn.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "csbindgenhandson";



        [DllImport(__DllName, EntryPoint = "rust_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int rust_add(int x, int y);

        [DllImport(__DllName, EntryPoint = "rust_pow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int rust_pow(int x, int y);


    }



}
